sudo: true

before_script:
  - sudo apt-get update -qq
  - sudo apt-get upgrade -y
  - sudo apt-get install iptables-dev libcap-dev

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
